# Generated by Django 5.0.4 on 2024-04-16 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='foto',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='idRol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.rol'),
        ),
        migrations.AddField(
            model_name='productos',
            name='Foto',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
