# Generated by Django 5.0.4 on 2024-05-17 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_ventas'),
    ]

    operations = [
        migrations.CreateModel(
            name='reseña',
            fields=[
                ('idreseña', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=200)),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.productos')),
            ],
        ),
    ]
