# Generated by Django 5.0.4 on 2024-05-20 03:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_idcompras_compras_idcompra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
