# Generated by Django 5.0.4 on 2024-05-20 19:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_ventas_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='fecha',
        ),
        migrations.AddField(
            model_name='compras',
            name='Fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
