# Generated by Django 5.0.4 on 2024-05-20 19:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_ventas_idcompra_remove_facturas_idventa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('idCompra', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Producto', models.IntegerField()),
                ('Cantidad', models.IntegerField()),
                ('Usuario', models.IntegerField()),
                ('Fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('idVenta', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Valor', models.FloatField()),
                ('Nventa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('idFactura', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('idcompra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.compras')),
            ],
        ),
        migrations.AddField(
            model_name='compras',
            name='idventa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.ventas'),
        ),
    ]
