# Generated by Django 5.0.4 on 2024-05-21 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_compras_ventas_facturas_compras_idventa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturas',
            name='idcompra',
        ),
        migrations.AddField(
            model_name='facturas',
            name='idventa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.ventas'),
            preserve_default=False,
        ),
    ]
