# Generated by Django 5.0.4 on 2024-05-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_remove_facturas_idcompra_facturas_idventa'),
    ]

    operations = [
        migrations.CreateModel(
            name='actividades',
            fields=[
                ('idactividad', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=200)),
                ('involucrado', models.IntegerField()),
            ],
        ),
    ]
