# Generated by Django 5.0.4 on 2024-05-22 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_actividades_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('idrepartidor', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('estador', models.IntegerField()),
                ('Venta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.ventas')),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.usuarios')),
            ],
        ),
    ]
