# Generated by Django 5.0.4 on 2024-08-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_repartidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repartidor',
            name='estador',
            field=models.IntegerField(default=1),
        ),
    ]
